@echo off
echo Starting FarmToForkLedger...
echo Starting backend server...
start "" cmd /k "cd server && npm start"
echo Waiting for backend to start...
timeout /t 5 >nul
echo Starting frontend client...
start "" cmd /k "cd client && npm start"
echo Both servers started. Check the new windows.